import axios from 'axios';
import Head from 'next/head';
import { useRef, useState } from 'react';
import { ProductSelect } from '../../../../components/v1/Index';
import useUserStore from '../../../../features/userStore';
import baseUrl from '../../../../utils/v1/baseUrl';
import { useDownloadExcel } from 'react-export-table-to-excel';
import { useReactToPrint } from 'react-to-print';

export default function Raw({ products }) {
  const { user } = useUserStore();
  const printRef = useRef();
  const excelRef = useRef()
  const [product, setProduct] = useState({})
  console.log(product)
  const handlePrint = useReactToPrint({
    content: () => printRef.current,
    documentTitle : product?.name + " [Version-"+product?.version+"]"
  });

  const { onDownload } = useDownloadExcel({
    currentTableRef: excelRef.current,
    filename: `${product?.section} - ${product?.name} [v-${product?.version}]`,
    sheet: product?.name
  });
  return (
    <div className='raw-consumption'>
      <Head>
        <title>Check your recipes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <div className='raw print:mx-12' ref={printRef}>
        <div>
          <div className='space-y-2 py-2 print:space-y-0 print:flex justify-between print:space-x-4 print:p-2 print:text-sm'>
            <ProductSelect {...{products,setProduct }} />
          </div>
        </div>
      </div>
    </div>
  );
}

export async function getServerSideProps(context) {
  const { section } = context.params
    try {
        const { data } = await axios.get(`${baseUrl}/api/v1/products/${section}`)
        console.log(data);
        return {
            props: {
                products : data,
            },
        };
    } catch (error) {
        console.error('Error fetching products:', error.response ? error.response.data : error.message);
        return {
            props: {
                products: [],
            },
        };
    }
}