import Head from 'next/head'

export default function Raw() {

  return (
    <div className=''>
      <Head>
        <title>Fullstack Next Js Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='raw'>
        <div>
            <label htmlFor='section'>Section</label>
            <select>
                <option value=""></option>
            </select>
        </div>
      </div>
    </div>
  )
}
