const sectionsRange = {
    biscuit:{
      recipe_start_column : 'Z6',
      product_start_column : 'AA6',
      product_end_column: 'AB6',
      rm_start_row : 'AC6',
      rm_end_row : 'AD6',
      total_start_row : 'AE6',
      total_end_row : 'AF6',
      info_start_row : 'AG6',
      info_end_row : 'AH6',
      packing_start_row : 'AI6',
      packing_end_row : 'AJ6',
      carton_start_row : 'AK6',
      carton_end_row : 'AL6',
      total_column : 'AM6',
      pm_consumption_start_row : 'AN6',
      pm_consumption_end_row : 'AO6'
    },
    wafer:{
        recipe_start_column : 'Z7',
        product_start_column : 'AA7',
        product_end_column: 'AB7',
        rm_start_row : 'AC7',
        rm_end_row : 'AD7',
        total_start_row : 'AE7',
        total_end_row : 'AF7',
        info_start_row : 'AG7',
        info_end_row : 'AH7',
        packing_start_row : 'AI7',
        packing_end_row : 'AJ7',
        carton_start_row : 'AK7',
        carton_end_row : 'AL7',
        total_column : 'AM7',
        pm_consumption_start_row : 'AN7',
        pm_consumption_end_row : 'AO7'
    },
    cake:{
        recipe_start_column : 'Z8',
        product_start_column : 'AA8',
        product_end_column: 'AB8',
        rm_start_row : 'AC8',
        rm_end_row : 'AD8',
        total_start_row : 'AE8',
        total_end_row : 'AF8',
        info_start_row : 'AG8',
        info_end_row : 'AH8',
        packing_start_row : 'AI8',
        packing_end_row : 'AJ8',
        carton_start_row : 'AK8',
        carton_end_row : 'AL8',
        total_column : 'AM8',
        pm_consumption_start_row : 'AN8',
        pm_consumption_end_row : 'AO8'
    },
    snacks:{
      recipe_start_column : 'Z9',
      product_start_column : 'AA9',
      product_end_column: 'AB9',
      rm_start_row : 'AC9',
      rm_end_row : 'AD9',
      total_start_row : 'AE9',
      total_end_row : 'AF9',
      info_start_row : 'AG9',
      info_end_row : 'AH9',
      packing_start_row : 'AI9',
      packing_end_row : 'AJ9',
      carton_start_row : 'AK9',
      carton_end_row : 'AL9',
      total_column : 'AM9',
      pm_consumption_start_row : 'AN9',
      pm_consumption_end_row : 'AO9'
    },
    lachcha:{
        recipe_start_column : 'Z10',
        product_start_column : 'AA10',
        product_end_column: 'AB10',
        rm_start_row : 'AC10',
        rm_end_row : 'AD10',
        total_start_row : 'AE10',
        total_end_row : 'AF10',
        info_start_row : 'AG10',
        info_end_row : 'AH10',
        packing_start_row : 'AI10',
        packing_end_row : 'AJ10',
        carton_start_row : 'AK10',
        carton_end_row : 'AL10',
        total_column : 'AM10',
        pm_consumption_start_row : 'AN10',
        pm_consumption_end_row : 'AO10'
    },
    chocolate:{
        recipe_start_column : 'Z1',
        product_start_column : 'AA1',
        product_end_column: 'AB1',
        rm_start_row : 'AC1',
        rm_end_row : 'AD1',
        total_start_row : 'AE1',
        total_end_row : 'AF1',
        info_start_row : 'AG1',
        info_end_row : 'AH1',
        packing_start_row : 'AI1',
        packing_end_row : 'AJ1',
        carton_start_row : 'AK1',
        carton_end_row : 'AL1',
        total_column : 'AM1',
        pm_consumption_start_row : 'AN1',
        pm_consumption_end_row : 'AO1'
    },
    noodles:{
        recipe_start_column : 'Z12',
        product_start_column : 'AA12',
        product_end_column: 'AB12',
        rm_start_row : 'AC12',
        rm_end_row : 'AD12',
        total_start_row : 'AE12',
        total_end_row : 'AF12',
        info_start_row : 'AG12',
        info_end_row : 'AH12',
        packing_start_row : 'AI12',
        packing_end_row : 'AJ12',
        carton_start_row : 'AK12',
        carton_end_row : 'AL12',
        total_column : 'AM12',
        pm_consumption_start_row : 'AN12',
        pm_consumption_end_row : 'AO12'
    },
    vermicelli:{
        recipe_start_column : 'Z13',
        product_start_column : 'AA13',
        product_end_column: 'AB13',
        rm_start_row : 'AC13',
        rm_end_row : 'AD13',
        total_start_row : 'AE13',
        total_end_row : 'AF13',
        info_start_row : 'AG13',
        info_end_row : 'AH13',
        packing_start_row : 'AI13',
        packing_end_row : 'AJ13',
        carton_start_row : 'AK13',
        carton_end_row : 'AL13',
        total_column : 'AM13',
        pm_consumption_start_row : 'AN13',
        pm_consumption_end_row : 'AO13'
    }
}